### ISSUE TITLE
Field key doesn't have a default value

### ISSUE THREAD

**Issue by ghost** [pludoni/simple-captcha#7]
Hi,

We're seeing this error when trying to show a captcha with Rails 4.0.2:

"Mysql2::Error: Field 'key' doesn't have a default value: INSERT INTO `simple_captcha_data` (`created_at`, `updated_at`, `value`) VALUES (1388118456, 1388118456, 'VDFKK')"

We 'fixed' this by adding 'attr_accessible :key, :value' in lib/simple_captcha/simple_captcha_data.rb

**Comment by wpp** [comment]
Hi @zealot128 I just run into this again, but this time the initialiser is not an option.*

I was wondering wether a [change in](https://github.com/pludoni/simple-captcha/blob/master/lib/simple_captcha/simple_captcha_data.rb#L11):

    if defined? attr_protected                                                       
      attr_protected                                                                                                         
    end

would solve the issue a [couple of people are running into](http://stackoverflow.com/questions/21872465/simplecaptcha-image-not-loading-cant-mass-assign-protected-attributes). But looking [at git blame there seems to have been a good reason why it was changed](https://github.com/pludoni/simple-captcha/commit/03f99e73046f6bde0da03d9e2b02623768336c80). Do you happen to remember why that change was made? (Exclusive to Rails 3)?

*rails/rake will try to establish a database connection when compiling assets because of the initialiser.
